--db에 들어가는 데이터 작성
--member
insert into member(MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_ADDRESS, MEMBER_TEL, MEMBER_EMAIL, MEMBER_BIRTHDAY)
values ('a', '1234', 'aname', 'aadress', '0100000', 'a@a.com', '19951230');
insert into member(MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_ADDRESS, MEMBER_TEL, MEMBER_EMAIL, MEMBER_BIRTHDAY)
values ('b', '1234', 'bname', 'badress', '0200000', 'b@a.com', '19951230');
insert into member(MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_ADDRESS, MEMBER_TEL, MEMBER_EMAIL, MEMBER_BIRTHDAY)
values ('c', '1234', 'cname', 'cadress', '0300000', 'c@a.com', '19951230');
insert into member(MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_ADDRESS, MEMBER_TEL, MEMBER_EMAIL, MEMBER_BIRTHDAY)
values ('d', '1234', 'dname', 'dadress', '0400000', 'd@a.com', '19951230');
insert into member(MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_ADDRESS, MEMBER_TEL, MEMBER_EMAIL, MEMBER_BIRTHDAY)
values ('e', '1234', 'ename', 'eadress', '0500000', 'e@a.com', '19951230');
--findboard
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(1, '1title', '1content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(2, '2title', '2content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(3, '3title', '3content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(4, '4title', '4content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(5, '5title', '5content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(6, '6title', '6content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(7, '7title', '7content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(8, '8title', '8content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(9, '9title', '9content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(10, '10title', '10content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(11, '11title', '11content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(12, '12title', '12content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(13, '13title', '13content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(14, '14title', '14content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(15, '15title', '15content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(16, '16title', '16content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(17, '17title', '17content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(18, '18title', '18content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(19, '19title', '19content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(20, '20title', '20content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(21, '21title', '21content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(22, '21title', '21content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(23, '21title', '21content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(24, '21title', '21content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(25, '21title', '21content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(26, '21title', '21content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(27, '21title', '21content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(28, '21title', '21content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(29, '21title', '21content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(30, '21title', '21content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(31, '21title', '21content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(32, '21title', '21content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(33, '21title', '21content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);
insert into findboard(FINDBOARD_ID, FINDBOARD_TITLE, FINDBOARD_CONTENT, FINDBOARD_LOCATION, FINDBOARD_X, FINDBOARD_Y, FINDBOARD_STATUS, FINDBOARD_UPLOADTIME, FINDBOARD_TEL, FINDBOARD_NAME, FINDBOARD_READCOUNT, MEMBER_ID) 
values(34, '21title', '21content', '1location', '1x', '1y', '1', '200716', '0101111', 'aaa', 0, null);




